"""커뮤니티 크롤링 소스 정의 — rss_sources.py 패턴 재사용."""

COMMUNITY_SOURCES = [
    {
        "name": "fmkorea_humor",
        "base_url": "https://www.fmkorea.com/index.php?mid=humor&sort_index=pop&page=1",
        "site": "fmkorea",
        "board": "humor",
        "category": "humor",
        "weight": 1.3,
        "demographic_affinity": {"20s": 1.0, "30s": 0.8, "40s": 0.3},
    },
    {
        "name": "fmkorea_best",
        "base_url": "https://www.fmkorea.com/index.php?mid=best&sort_index=pop&page=1",
        "site": "fmkorea",
        "board": "best",
        "category": "trending",
        "weight": 1.4,
        "demographic_affinity": {"20s": 1.0, "30s": 0.9, "40s": 0.4},
    },
    {
        "name": "dcinside_best",
        "base_url": "https://gall.dcinside.com/board/lists/?id=dcbest",
        "site": "dcinside",
        "board": "dcbest",
        "category": "humor",
        "weight": 1.3,
        "demographic_affinity": {"20s": 1.0, "30s": 0.9, "40s": 0.4},
    },
    {
        "name": "theqoo_hot",
        "base_url": "https://theqoo.net/hot",
        "site": "theqoo",
        "board": "hot",
        "category": "trending",
        "weight": 1.2,
        "demographic_affinity": {"20s": 1.0, "30s": 0.9, "40s": 0.5},
    },
    {
        "name": "natepann_talk",
        "base_url": "https://pann.nate.com/talk/ranking",
        "site": "natepann",
        "board": "talk",
        "category": "empathy",
        "weight": 1.1,
        "demographic_affinity": {"20s": 0.7, "30s": 1.0, "40s": 0.8},
    },
    {
        "name": "humoruniv_best",
        "base_url": "https://web.humoruniv.com/board/humor/list.html?table=pds&pg=0&st=day",
        "site": "humoruniv",
        "board": "best",
        "category": "humor",
        "weight": 1.0,
        "demographic_affinity": {"20s": 0.5, "30s": 0.9, "40s": 1.0},
    },
    {
        "name": "instiz_pt",
        "base_url": "https://www.instiz.net/pt?page=1&category=1",
        "site": "instiz",
        "board": "pt",
        "category": "trending",
        "weight": 1.1,
        "demographic_affinity": {"20s": 1.0, "30s": 0.7, "40s": 0.3},
    },
]
